---
- name: Check SSH service status
  hosts: localhost
  connection: local
  become: true

  tasks:
    - name: Check SSH service status
      service:
        name: ssh
        state: started
      register: ssh_service_status

    - name: Print SSH servic status
      debug:
        msg: "SSH service is {{ ssh_service_status.state }}"
